/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarievenRouteImport } from './routes/tarieven'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OverJoeyRouteImport } from './routes/over-joey'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const TarievenRoute = TarievenRouteImport.update({
  id: '/tarieven',
  path: '/tarieven',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OverJoeyRoute = OverJoeyRouteImport.update({
  id: '/over-joey',
  path: '/over-joey',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/over-joey': typeof OverJoeyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarieven': typeof TarievenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/over-joey': typeof OverJoeyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarieven': typeof TarievenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/over-joey': typeof OverJoeyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarieven': typeof TarievenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/over-joey' | '/sitemap.xml' | '/tarieven'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/over-joey' | '/sitemap.xml' | '/tarieven'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/over-joey'
    | '/sitemap.xml'
    | '/tarieven'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  OverJoeyRoute: typeof OverJoeyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TarievenRoute: typeof TarievenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarieven': {
      id: '/tarieven'
      path: '/tarieven'
      fullPath: '/tarieven'
      preLoaderRoute: typeof TarievenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-joey': {
      id: '/over-joey'
      path: '/over-joey'
      fullPath: '/over-joey'
      preLoaderRoute: typeof OverJoeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  OverJoeyRoute: OverJoeyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TarievenRoute: TarievenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
